apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    component: istio-base
  name: cnoe-dev-istio-base-manual
  namespace: argo-cd
spec:
  destination:
    namespace: istio-system
    name: cnoe-dev
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    jqPathExpressions:
    - .webhooks[].failurePolicy
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
  project: default
  source:
    chart: base
    helm:
      releaseName: istio-base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
