apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cnoe-dev-cert
  namespace: istio-gateway
spec:
  commonName: "*.cnoe-dev.nexus.ripplenet.dev"
  dnsNames:
    - "*.cnoe-dev.nexus.ripplenet.dev"
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-dns
  renewBefore: 720h0m0s
  secretName: cnoe-dev-cert
