apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
       route53:
         hostedZoneID: Z048723722W20IHB5KCFH
         region: us-west-2
      selector:
        dnsZones:
        - cnoe-dev.nexus.ripplenet.dev
